# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lordviktor's blog
email: victorjspinto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog contendo alguns id√©ias e mostrando um pouco do meu trabalho no Github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lordviktor.github.io" # the base hostname & protocol for your site
github_username:  lordviktor

# Build settings
markdown: kramdown
